language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.3
  - 2.1.5
  - 2.0.0
gemfile:
  - Gemfile
  - ruby200-215.Gemfile
matrix:
  exclude:
    - rvm: 2.4.0
      gemfile: ruby200-215.Gemfile
    - rvm: 2.3.3
      gemfile: ruby200-215.Gemfile
    - rvm: 2.2.3
      gemfile: ruby200-215.Gemfile
    - rvm: 2.1.5
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
